
name: project-environment
channels:
  - conda-forge #i believe this is where python pulls packages from if doing conda installs. 
  - defaults
dependencies:
  # I learned that in python 3.9+ type-hinting doesn't require imports. 
  # Additionally, pyGMM requires Python 3.10+
  - python=3.11 
  - numpy=1.26.4 #The original package specifics will be overwritten after first run
  - scipy=1.14.1
  - pandas>=2.0,<3.0
  - pathlib
  - pyyaml
  - pyproj
  - matplotlib
  - math
  - flake8
  - pytest
  - scikit-learn
  - pip
  - pip:
    - pyGMM==0.8.0


# IF MAKING UPDATE TO THIS SCRIPT:
# conda env update -f environment.yml --prune (to add and remove unused libraries)

# EACH TIME RE-OPENING SCRIPT Aug 5, 2026
# cd /workspaces/Spatial-Geostatistics-Analysis
# Then run:
# conda activate project-environment
# Then fi you're linting:
# flake8 src

# For the first time setting dependencies (or updating them): Aug 3/4 2026
# 1. Write code 
# 2. Run 'conda install numpy scipy pandas' and/or  'pip install scikit-gstat' to install packages, 
#    as needed (conda install rather than pip for the general packages to keep things organized with the YAML)  
# 3. Then pin the exact dependencies using  'conda env export --no-builds > environment.yml' - it updates the yaml
#then stage and commit as usual
#these dependencies from the env file will be utilized each time the CI workflow runs.

# In the case that the script needs to re-sync wth this env file at the start of running: conda env create -f environment.yml

# Note: spaces in this file are not standard
