# Filename : config.yaml
# Author : Chelsea Momoh
# Date : 2026-11-03
# Version : 1.0
# Description : This script will contain all configurations for analyses.
# * - * - * - * - * - * - * - * - * - * - * - * - * - * - * -


---
# Firstly, lag interval and bin width.
# units in km
lag_interval: 1.8 
bin_width: 1.5

...